// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Generate a random 256-bit encryption key
Uint8List generateKey() => RustLib.instance.api.crateCryptoGenerateKey();

/// Encrypt plaintext using AES-256-GCM
///
/// Returns: nonce (12 bytes) || ciphertext || tag (16 bytes)
Uint8List encryptText({required String plaintext, required List<int> key}) =>
    RustLib.instance.api.crateCryptoEncryptText(plaintext: plaintext, key: key);

/// Decrypt ciphertext using AES-256-GCM
///
/// Expects: nonce (12 bytes) || ciphertext || tag (16 bytes)
String decryptText({required List<int> ciphertext, required List<int> key}) =>
    RustLib.instance.api.crateCryptoDecryptText(ciphertext: ciphertext, key: key);
